#!/bin/sh

# Actualitza el gestor de paquets
apk update

# Instal·la Apache
apk add apache2

# Inicia Apache i establix-lo perquè s'iniciï automàticament en el reinici
rc-service apache2 start
rc-update add apache2 default

# Exemple: Crea una pàgina d'inici per Apache
echo "<html><body><h1>Apache està instal·lat i funcionant!</h1></body></html>" > /var/www/localhost/htdocs/index.html

# Final de la instal·lació
echo "Instal·lació d'Apache completa!"
